In [ ]:
from PIL import Image
import numpy as np
import os
if os.name == "nt":
    import msvcrt
else:
    import tty
    import termios
from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt
import cv2 as cv
import random
from math import log
import pandas
# from google.colab.patches import cv2_imshow
from tqdm import tqdm
import image_tools as it

In [ ]:
#全黑的灰度图
gray0=np.zeros((500,500),dtype=np.uint8)
cv.imwrite('graphs\solid-color\\gray-black.png',gray0)

#全白的灰度图
gray0[:,:]=255
gray255=gray0[:,:]
cv.imwrite('graphs\solid-color\\gray-white.png',gray255)
#将灰度图转换成彩色图
Img_rgb=cv.cvtColor(gray255,cv.COLOR_GRAY2RGB)
#将RGB通道全部置成0
Img_rgb[:,:,0:3]=0
cv.imwrite('graphs\solid-color\\rgb-black.png',Img_rgb)
#将RGB通道全部置成255
Img_rgb[:,:,0:3]=255
cv.imwrite('graphs\solid-color\\rgb-white.png',Img_rgb)

In [12]:
# #全黑的灰度图
# gray0=np.zeros((500,500),dtype=np.uint8)
# cv.imwrite('graphs\solid-color\\gray-black.png',gray0)

# #全白的灰度图
# gray0[:,:]=255
# gray255=gray0[:,:]
# cv.imwrite('graphs\solid-color\\gray-white.png',gray255)
# #将灰度图转换成彩色图
# Img_rgb=cv.cvtColor(gray255,cv.COLOR_GRAY2RGB)
# #将RGB通道全部置成0
# Img_rgb[:,:,0:3]=0
# cv.imwrite('graphs\solid-color\\rgb-black.png',Img_rgb)
# #将RGB通道全部置成255
# Img_rgb[:,:,0:3]=255
# cv.imwrite('graphs\solid-color\\rgb-white.png',Img_rgb)

orange = np.zeros((500, 500,3), dtype=np.uint8)
print()
for i in range(500):
    for j in range(500):
        orange[i][j] = (0, 195, 255)
cv.imwrite('graphs\solid-color\\rgb-orange.png',orange)
img = it.get_image_color('graphs\solid-color\\rgb-orange.png')

print(img)



[[[  0 195 255]
  [  0 195 255]
  [  0 195 255]
  ...
  [  0 195 255]
  [  0 195 255]
  [  0 195 255]]

 [[  0 195 255]
  [  0 195 255]
  [  0 195 255]
  ...
  [  0 195 255]
  [  0 195 255]
  [  0 195 255]]

 [[  0 195 255]
  [  0 195 255]
  [  0 195 255]
  ...
  [  0 195 255]
  [  0 195 255]
  [  0 195 255]]

 ...

 [[  0 195 255]
  [  0 195 255]
  [  0 195 255]
  ...
  [  0 195 255]
  [  0 195 255]
  [  0 195 255]]

 [[  0 195 255]
  [  0 195 255]
  [  0 195 255]
  ...
  [  0 195 255]
  [  0 195 255]
  [  0 195 255]]

 [[  0 195 255]
  [  0 195 255]
  [  0 195 255]
  ...
  [  0 195 255]
  [  0 195 255]
  [  0 195 255]]]
