In [ ]:
from PIL import Image
import numpy as np
import os
if os.name == "nt":
    import msvcrt
else:
    import tty
    import termios
from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt
import cv2 as cv
import random
from math import log
import pandas
# from google.colab.patches import cv2_imshow
from tqdm import tqdm
import image_tools as it

In [ ]:
#全黑的灰度图
gray0=np.zeros((500,500),dtype=np.uint8)
cv.imwrite('graphs\solid-color\\gray-black.png',gray0)

#全白的灰度图
gray0[:,:]=255
gray255=gray0[:,:]
cv.imwrite('graphs\solid-color\\gray-white.png',gray255)
#将灰度图转换成彩色图
Img_rgb=cv.cvtColor(gray255,cv.COLOR_GRAY2RGB)
#将RGB通道全部置成0
Img_rgb[:,:,0:3]=0
cv.imwrite('graphs\solid-color\\rgb-black.png',Img_rgb)
#将RGB通道全部置成255
Img_rgb[:,:,0:3]=255
cv.imwrite('graphs\solid-color\\rgb-white.png',Img_rgb)

In [11]:
# #全黑的灰度图
# gray0=np.zeros((500,500),dtype=np.uint8)
# cv.imwrite('graphs\solid-color\\gray-black.png',gray0)

# #全白的灰度图
# gray0[:,:]=255
# gray255=gray0[:,:]
# cv.imwrite('graphs\solid-color\\gray-white.png',gray255)
# #将灰度图转换成彩色图
# Img_rgb=cv.cvtColor(gray255,cv.COLOR_GRAY2RGB)
# #将RGB通道全部置成0
# Img_rgb[:,:,0:3]=0
# cv.imwrite('graphs\solid-color\\rgb-black.png',Img_rgb)
# #将RGB通道全部置成255
# Img_rgb[:,:,0:3]=255
# cv.imwrite('graphs\solid-color\\rgb-white.png',Img_rgb)

orange = np.zeros((500, 500,3), dtype=np.uint8)
print()
for i in range(500):
    for j in range(500):
        orange[i][j] = (0, 195, 255)
cv.imwrite('graphs\solid-color\\rgb-orange.png',orange)
img = it.get_image_color('graphs\solid-color\\rgb-orange.png')

print(img)



[[[139 139 139]
  [118 118 118]
  [109 109 109]
  ...
  [131 131 131]
  [ 48  48  48]
  [ 71  71  71]]

 [[240 240 240]
  [ 19  19  19]
  [178 178 178]
  ...
  [105 105 105]
  [218 218 218]
  [196 196 196]]

 [[ 95  95  95]
  [ 33  33  33]
  [164 164 164]
  ...
  [ 25  25  25]
  [111 111 111]
  [135 135 135]]

 ...

 [[ 87  87  87]
  [169 169 169]
  [ 90  90  90]
  ...
  [ 16  16  16]
  [  9   9   9]
  [ 12  12  12]]

 [[154 154 154]
  [ 53  53  53]
  [191 191 191]
  ...
  [ 64  64  64]
  [ 49  49  49]
  [231 231 231]]

 [[139 139 139]
  [  2   2   2]
  [179 179 179]
  ...
  [ 44  44  44]
  [ 70  70  70]
  [129 129 129]]]
