In [63]:
from PIL import Image
import numpy as np
import os

if os.name == "nt":
    import msvcrt
else:
    import tty
    import termios
from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt
import cv2 as cv
import random
from math import log
import pandas

# from google.colab.patches import cv2_imshow
from tqdm import tqdm
import image_tools as it
from hashlib import sha256
import math

In [ ]:
# def rgb_to_img(rows,cols,r,g,b):
#     img = []
#     for i in range(rows):
#         curr = []
#         for j in range(cols):
#             curr.append([r[i][j],g[i][j],b[i][j]])
#         img.append(curr)
#     return img


In [ ]:
img = it.get_image_rgb("graphs\orig.png")
print(type(img))
r, g, b = it.get_rgb_arr2(img, fmt="rgb")  # r g b 都是2维数组
plt.imshow(img)  # rgb


In [ ]:
row, col, n = img.shape
newimg = it.rgb_to_img(row, col, r, g, b)
# print(newimg)
plt.imshow(newimg)


In [ ]:
# 垂直方向互换
temp_r = r[:]  # 拷贝 直接为r则引用
temp_g = g[:]
temp_b = b[:]
# print(temp_r)
# random.shuffle(img)
random.shuffle(temp_r)
random.shuffle(temp_g)
random.shuffle(temp_b)
shuffled_img = it.rgb_to_img(row, col, temp_r, temp_g, temp_b)

# 水平方向互换
shuffled_img2 = np.array(shuffled_img)
shuffled_img2 = shuffled_img2.transpose(1, 0, 2)
r2, g2, b2 = it.get_rgb_arr2(shuffled_img2, "rgb")
random.shuffle(r2)
random.shuffle(g2)
random.shuffle(b2)
shuffled_img2 = it.rgb_to_img(row, col, r2, g2, b2)
plt.imshow(shuffled_img2)
cv.imwrite("test.png", np.asarray(shuffled_img2))


In [ ]:
def fractal_shuffle(matrix):
    rows, cols = matrix.shape
    if rows == 1 and cols == 1:
        return matrix

    # 按行和列将当前矩阵分解成四个子矩阵
    mid_row, mid_col = rows // 2, cols // 2  # // 整除
    matrix_parts = [
        matrix[:mid_row, :mid_col],  # 左上
        matrix[:mid_row, mid_col:],  # 右上
        matrix[mid_row:, :mid_col],  # 左下
        matrix[mid_row:, mid_col:],  # 右下
    ]

    # 对四个子矩阵进行递归打乱
    shuffled_parts = []
    for part in matrix_parts:
        shuffled_parts.append(fractal_shuffle(part))

    # 将打乱过的子矩阵合并成一个新矩阵
    shuffled_matrix = np.vstack(
        [
            np.hstack([shuffled_parts[0], shuffled_parts[1]]),
            np.hstack([shuffled_parts[2], shuffled_parts[3]]),
        ]
    )

    return shuffled_matrix


# 示例用法
import numpy as np

matrix = np.arange(16).reshape(4, 4)  # 创建一个4x4的矩阵
shuffled_matrix = fractal_shuffle(matrix)  # 打乱矩阵
print(shuffled_matrix)  # 输出打乱后的矩阵
# 输出：
# [[ 6  2 10 14]
#  [ 4  5  7 11]
#  [ 0  9  1 15]
#  [12  8 13  3]]

# 使用同样的算法还原原始矩阵
restored_matrix = fractal_shuffle(shuffled_matrix)
print(restored_matrix)  # 输出还原后的矩阵
# 输出：
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]
#  [12 13 14 15]]

# 比较还原后的矩阵和原始矩阵是否相等
assert np.array_equal(matrix, restored_matrix)


In [ ]:
# img : img matrix
# key : sha256
def shuffle(img, key):
    return


img_file = open("graphs\orig.png", "rb")
sha26_str = sha256(img_file.read()).hexdigest()

img = it.get_image_color("graphs\orig.png")


In [ ]:
# import hashlib
# from PIL import Image
# import numpy as np

# # 获取SHA256密钥
# def get_key(img_path):
#     img_data = open(img_path, "rb").read()
#     key = hashlib.sha256(img_data).hexdigest()
#     return key

# # 图像混淆
# def shuffle_image(img_path, key):
#     # 打开图像，并将其转换为numpy数组
#     img = Image.open(img_path)
#     img_arr = np.array(img)

#     # 将密钥转换为numpy数组，并将其大小调整为与图像大小一致
#     key_arr = np.array([int(c, 16) for c in key]).reshape(img_arr.shape)

#     # 将图像混淆，通过对每个像素的密钥值进行排序
#     img_arr_shuffled = np.zeros_like(img_arr)
#     for i in range(img_arr.shape[0]):
#         for j in range(img_arr.shape[1]):
#             key_ij = key_arr[i, j]
#             row = img_arr[i]
#             row_shuffled = np.zeros_like(row)
#             for k in range(row.shape[0]):
#                 row_shuffled[k] = row[(k+key_ij)%row.shape[0]]
#             img_arr_shuffled[i, j] = row_shuffled
#     return img_arr_shuffled

# # 还原原始图像
# def unshuffle_image(img_path, key):
#     # 打开图像，并将其转换为numpy数组
#     img = Image.open(img_path)
#     img_arr = np.array(img)

#     # 将密钥转换为numpy数组，并将其大小调整为与图像大小一致
#     key_arr = np.array([int(c, 16) for c in key]).reshape(img_arr.shape)

#     # 将图像还原
#     img_arr_unshuffled = np.zeros_like(img_arr)
#     for i in range(img_arr.shape[0]):
#         for j in range(img_arr.shape[1]):
#             key_ij = key_arr[i, j]
#             row = img_arr[i]
#             row_unshuffled = np.zeros_like(row)
#             for k in range(row.shape[0]):
#                 row_unshuffled[(k+key_ij)%row.shape[0]] = row[k]
#             img_arr_unshuffled[i, j] = row_unshuffled
#     return Image.fromarray(np.uint8(img_arr_unshuffled))

# # 示例
# img_path = "graphs\orig.png"
# key = get_key(img_path)
# img_arr_shuffled = shuffle_image(img_path, key)
# img_shuffled = Image.fromarray(np.uint8(img_arr_shuffled))
# img_shuffled.save("example_shuffled.png")
# img_unshuffled = unshuffle_image("example_shuffled.png", key)
# img_unshuffled.save("example_unshuffled.png")


In [125]:
map = {
    2: 256,
    3: 384,
    4: 512,
    5: 640,
    6: 768,
    7: 896,
    8: 1024,
    16: 2048
    # 256:2,
    # 384:3,
    # 512:4,
    # 640:5,
    # 768:6,
    # 896:7,
    # 1024:8,
    # 2048:16,
    # 4096:32
}


# 将图片矩阵填充为可整除的正方形矩阵，填充可能会很大，保证可以分成128块,
def fill_pic_to_square(img):
    # color or gray
    color = 1 if len(img.shape) == 3 else 0
    h, w = img.shape[:2]
    block_len = -1
    if max(h, w) < 2560:
        block_len = 128
    # print(color)
    print(h, " ", w)

    base_len = 128 * math.ceil(max(h, w) / block_len)  # 填充后的图片至少边长为base_len

    print("base len = ", base_len)
    fill_w = base_len - max(h, w)
    fill_h = base_len - min(h, w)
    print("fill w = ", fill_w)
    print("fill h = ", fill_h)

    # 创建空白的正方形图片，并将原始图片复制到左上方
    if color:
        square_image = np.zeros((base_len, base_len, 3), dtype=np.uint8)
    else:
        square_image = np.zeroes((base_len, base_len), dtype=np.uint8)
    square_image[0:h, 0:w] = img

    # 显示结果
    cv.imshow("fill to square image", square_image)
    cv.waitKey(0)
    cv.destroyAllWindows()
    return


# 将图片矩阵填充，只填充小部分，使其h w都可整除一个数即可，长度不到1280保证可以分成128块，超过则保证每小块边最多10个像素
def fill_pic(img):
    # color or gray
    color = 1 if len(img.shape) == 3 else 0
    block_len = -1
    h, w = img.shape[:2]
    if max(h, w) < 1280:
        block_len = 128
    else:
        block_len = math.ceil(max(h, w) / 10)
    # print(color)
    print(h, " ", w)
    min_divisible_num = math.ceil(max(h, w) / block_len)
    # print('base len = ',base_len)
    print('block_len = ',block_len)
    print("min_divisible_num = ", min_divisible_num)
    base_w = min_divisible_num * math.ceil(w / min_divisible_num)  #
    base_h = min_divisible_num * math.ceil(h / min_divisible_num)

    fill_w = base_w - w
    fill_h = base_h - h
    print("base w = ", base_w, "fill w = ", fill_w)
    print("base h = ", base_h, "fill h = ", fill_h)

    # 创建空白的正方形图片，并将原始图片复制到左上方
    if color:
        square_image = np.zeros((base_h, base_w, 3), dtype=np.uint8)
    else:
        square_image = np.zeroes((base_h, base_w), dtype=np.uint8)
    square_image[0:h, 0:w] = img

    # 显示结果
    cv.imshow("fill image 2", square_image)
    cv.waitKey(0)
    cv.destroyAllWindows()
    return min_divisible_num


# print(128*math.ceil(385/128))


In [127]:
img_path = "graphs\\fill-image\\1351_805.png"
# graphs\fill-image\273_531.png
img = it.get_image_matrix(img_path, 1)

fill_pic2(img)

805   1351
block_len =  136
min_divisible_num =  10
base w =  1360 fill w =  9
base h =  810 fill h =  5


10